server.port=7000

# Enable hot deployment
spring.devtools.restart.enabled=true

# Specify the directory files need to restart
spring.devtools.restart.additional-paths=src/main/java

# Exclude directory files that do not need to restart
# spring.devtools.restart.exclude=static/**, public/**, WEB-INF/**